[build]
  command = "npm install -g @angular/cli && npm install && ng build --configuration production"
  publish = "portfolio-website/dist/portfolio-website"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
