[build]
  command = "npm install -g @angular/cli && npm install && ng build --configuration production"
  publish = "dist/portfolio-website"

[build.environment]
  NODE_VERSION = "20.19.0"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
